openapi: 3.0.0
info:
  title: Boutique-hotel-technikum-2024-b_anditen API
  description: API for managing room bookings at Boutique Hotel Technikum.
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/v1/
    description: Local server
paths:
  /rooms:
    get:
      summary: List all rooms
      operationId: listRooms
      parameters:
        - name: filter
          in: query
          required: false
          description: Optional filters for the room
          schema:
            type: array
            items:
              type: object
              properties:
                startDate:
                  type: string
                  format: date
                  description: Filter rooms by start date
                endDate:
                  type: string
                  format: date
                  description: Filter rooms by end date
      responses:
        '200':
          description: A list of rooms
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: array
                    items:
                      $ref: '#/components/schemas/Room'
  /bookings:
    post:
      summary: Create a new booking
      operationId: createBooking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '200':
          description: Booking created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingConfirmation'
components:
  schemas:
    Room:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        pricePerNight:
          type: number
        extras:
          type: array
          items:
            type: string
        imageUrl:
          type: string
          format: uri
          description: URL of the room image
        available:
          type: boolean
    BookingRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - birthdate
        - breakfast
        - roomId
        - startDate
        - endDate
        - guestCount
      properties:
        roomId:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        birthdate:
          type: string
          format: date
        breakfast:
          type: boolean
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        guestCount:
          type: integer
    BookingConfirmation:
      type: object
      properties:
        bookingId:
          type: integer
        room:
          $ref: '#/components/schemas/Room'
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
        guestInfo:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
            guestCount:
              type: integer
        totalCost:
          type: number
        directions:
          type: string
        contact:
          type: string
